version: 2
updates:
  # Maintain dependencies for each example folder
  - package-ecosystem: "npm"
    directory: "/examples/typescript-cron-lambda"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automerge"
      - "auto-approve"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/examples/typescript-manual-mapping"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automerge"
      - "auto-approve"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/examples/typescript-step-functions"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automerge"
      - "auto-approve"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/examples/typescript-step-functions-mixed"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automerge"
      - "auto-approve"
    open-pull-requests-limit: 5
